In [1]:
import numpy as np

# Learn Numpy

#### 1D Array

In [13]:
one_dim_array = np.array(range(1,6))
one_dim_array.ndim

1

#### 2D Array

In [17]:
two_dim_array = np.array([list(range(1,4)), list(range(4,7))])
print(two_dim_array)
print(two_dim_array.ndim)

[[1 2 3]
 [4 5 6]]
2


#### 3D Array

In [28]:
l1 = [list(range(1,4)), list(range(4,7)), list(range(7,10))]
l2 = [list(range(10,13)), list(range(13,16)), list(range(16,19))]
three_dim_array = np.array([l1, l2])
print(three_dim_array)
print(three_dim_array.ndim)

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[10 11 12]
  [13 14 15]
  [16 17 18]]]
3


#### Accessing Elements

In [32]:
print(two_dim_array[1,2])
print(three_dim_array[0])

6
[[1 2 3]
 [4 5 6]
 [7 8 9]]


#### Slicing

In [40]:
nums = np.array([1,2,3,4,5,6])
result = nums[0:5:2]
result

array([1, 3, 5])

#### BroadCasting

In [42]:
one_dim_array - 2

array([-1,  0,  1,  2,  3])

In [1]:
%load_ext line_profiler

ModuleNotFoundError: No module named 'line_profiler'